routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
//routes yang menangani aktivasi
Route::get('auth/activate', 'Auth\ActivationController@activate')->name('auth.activate');

//routes yang menangani resend aktivasi email
Route::get('auth/activate/resend', 'Auth\ActivationResendController@showResendForm')->name('auth.activate.resend');
Route::post('auth/activate/resend', 'Auth\ActivationResendController@resend');

Route::get('/home', 'HomeController@index')->name('home');


//routes yang menangani backend
Route::resource('/backend/users', 'UsersController', ['as' => 'backend']);
Route::resource('/backend/categories', 'CategoriesController', ['as' => 'backend']);
Route::resource('/backend/products', 'ProductsController', ['as' => 'backend']);
Route::get('/backend/home', 'HomeController@index')->name('backend.home');


//routes yang menangani api
Route::group(['middleware' => 'auth'], function () {
    Route::get('/api/datatable/users', 'UsersController@dataTable')->name('api.datatable.users');
    Route::get('/api/datatable/categories', 'CategoriesController@dataTable')->name('api.datatable.categories');
    Route::get('/api/datatable/products', 'ProductsController@dataTable')->name('api.datatable.products');
    Route::get('/api/datatable/comments', 'CommentsController@dataTable')->name('api.datatable.comments');
});

Route::get('/abouts', 'AboutsController@index')->name('abouts');

resources/views/backend/partials/_action.blade.php
{!! Form::model($model, ['url' => $delete_url, 'method' => 'DELETE']) !!}
    <a href="{{ $show_url }}" class="btn btn-sm btn-outline-info" style="padding-bottom: 0px; padding-top: 0px;">
        Show
        <span class="btn-label btn-label-right"><i class="fa fa-eye"></i></span>
    </a>
    <a href="{{ $edit_url }}" class="btn btn-sm btn-outline-secondary" style="padding-bottom: 0px; padding-top: 0px;">
        Edit
        <span class="btn-label btn-label-right"><i class="fa fa-edit"></i></span>
    </a>
    <button  
        type="submit" class="btn btn-sm btn-outline-danger" 
        style="padding-bottom: 0px; padding-top: 0px;"
        onclick="return confirm('Yakin Ingin Menghapus?');"
    >
        Delete
        <span class="btn-label btn-label-right"><i class="fa fa-trash"></i></span>
    </button>
{!! Form::close() !!}

resources/views/backend/partials/_navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{{ route('backend.home') }}"><img src="{{ asset('frontend/images/logo.png') }}" alt="logo"></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
            <a class="nav-link" href="{{ route('backend.home') }}">
            <i class="fa fa-fw fa-home"></i>
            <span class="nav-link-text">Dashboard</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Category">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-pencil"></i>
            <span class="nav-link-text">Category</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseMulti">
            <li>
                <a href="{{ route('backend.categories.index') }}">Semua Category</a>
            </li>
            <li>
                <a href="{{ route('backend.categories.create') }}">Tambahkan Category</a>
            </li>
            </ul>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Product">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-pencil"></i>
            <span class="nav-link-text">Product</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseMulti2">
            <li>
                <a href="{{ route('backend.products.index') }}">Semua Product</a>
            </li>
            <li>
                <a href="{{ route('backend.products.create') }}">Tambahkan Product</a>
            </li>
            </ul>
        </li>
        {{-- 
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Comments">
            <a class="nav-link" href="#">
            <i class="fa fa-fw fa-comments"></i>
            <span class="nav-link-text">Comments</span>
            </a>
        </li> --}}
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Users">
            <a class="nav-link" href="{{ route('backend.users.index') }}">
            <i class="fa fa-fw fa-users"></i>
            <span class="nav-link-text">Users</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Settings">
            <a class="nav-link" href="#">
            <i class="fa fa-fw fa-gears"></i>
            <span class="nav-link-text">Settings</span>
            </a>
        </li>

        </ul>
        <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
            </a>
        </li>

        </ul>
        <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a href="{{ url('/') }}" class="nav-link">
            <i class="fa fa-fw fa-sign-in"></i>Site</a>
        </li>

        <li class="nav-item">
            <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for...">
                <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fa fa-search"></i>
                </button>
                </span>
            </div>
            </form>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
        </ul>
    </div>
</nav>